In [92]:
import anndata
import pandas as pd
import numpy as np

# Purpose of script

Group the GTEx data by organism part stratificataion and take the average expression. 

Just like with the single cell. Except we don't have cell info here so we arn't grouping with that as well

In [93]:
adata = anndata.read_h5ad('../../../../../pipeline42/datasets/Gtex/GTEx.h5ad')

In [94]:
adata.obs

SAMPID            SMTS  \
SAMPID                                                               
GTEX-1117F-0226-SM-5GZZ7  GTEX-1117F-0226-SM-5GZZ7  Adipose Tissue   
GTEX-1117F-0426-SM-5EGHI  GTEX-1117F-0426-SM-5EGHI          Muscle   
GTEX-1117F-0526-SM-5EGHJ  GTEX-1117F-0526-SM-5EGHJ    Blood Vessel   
GTEX-1117F-0626-SM-5N9CS  GTEX-1117F-0626-SM-5N9CS    Blood Vessel   
GTEX-1117F-0726-SM-5GIEN  GTEX-1117F-0726-SM-5GIEN           Heart   
...                                            ...             ...   
GTEX-ZZPU-2126-SM-5EGIU    GTEX-ZZPU-2126-SM-5EGIU           Ovary   
GTEX-ZZPU-2226-SM-5EGIV    GTEX-ZZPU-2226-SM-5EGIV          Vagina   
GTEX-ZZPU-2426-SM-5E44I    GTEX-ZZPU-2426-SM-5E44I    Blood Vessel   
GTEX-ZZPU-2626-SM-5E45Y    GTEX-ZZPU-2626-SM-5E45Y          Muscle   
GTEX-ZZPU-2726-SM-5NQ8O    GTEX-ZZPU-2726-SM-5NQ8O  Adipose Tissue   

                                             SMTSD  
SAMPID                                              
GTEX-1117F-0226-SM-5GZZ7    Adipose - Subcutaneous  
GTEX-1117F-0426-SM-5EGHI         Muscle - Skeletal  
GTEX-1117F-0526-SM-5EGHJ           Artery - Tibial  
GTEX-1117F-0626-SM-5N9CS         Artery - Coronary  
GTEX-1117F-0726-SM-5GIEN  Heart - Atrial Appendage  
...                                            ...  
GTEX-ZZPU-2126-SM-5EGIU                      Ovary  
GTEX-ZZPU-2226-SM-5EGIV                     Vagina  
GTEX-ZZPU-2426-SM-5E44I            Artery - Tibial  
GTEX-ZZPU-2626-SM-5E45Y          Muscle - Skeletal  
GTEX-ZZPU-2726-SM-5NQ8O     Adipose - Subcutaneous  

[17382 rows x 3 columns]

In [99]:
SMTS = adata.obs['SMTS'].unique()

In [100]:
example = adata[adata.obs['SMTS'] == SMTS[0]]

In [101]:
example.X

ArrayView([[0.000e+00, 8.764e+00, 0.000e+00, ..., 4.592e+00, 1.674e+01,
            2.430e+01],
           [0.000e+00, 5.389e+00, 0.000e+00, ..., 1.197e+00, 9.377e+00,
            8.912e+00],
           [0.000e+00, 8.380e-01, 0.000e+00, ..., 3.229e+00, 1.517e+01,
            5.419e+00],
           ...,
           [0.000e+00, 4.201e+00, 0.000e+00, ..., 3.657e+00, 1.112e+01,
            0.000e+00],
           [0.000e+00, 1.454e+00, 0.000e+00, ..., 3.249e+00, 3.778e+01,
            0.000e+00],
           [2.522e-02, 2.167e+00, 0.000e+00, ..., 3.357e+00, 1.395e+01,
            0.000e+00]], dtype=float32)

In [29]:
genewise_average = np.mean(example.X, axis = 0)

In [91]:
adata.X

array([[0.000e+00, 8.764e+00, 0.000e+00, ..., 4.592e+00, 1.674e+01,
        2.430e+01],
       [0.000e+00, 3.861e+00, 0.000e+00, ..., 2.339e+00, 2.824e+01,
        6.247e+00],
       [0.000e+00, 7.349e+00, 1.004e+00, ..., 3.886e+00, 1.517e+01,
        2.511e+01],
       ...,
       [0.000e+00, 2.857e+00, 0.000e+00, ..., 3.151e+00, 1.081e+01,
              nan],
       [1.965e-02, 8.696e-01, 0.000e+00, ..., 1.662e+00, 3.447e+01,
              nan],
       [2.522e-02, 2.167e+00, 0.000e+00, ..., 3.357e+00, 1.395e+01,
              nan]], dtype=float32)

In [112]:

def create_OP_list(adata, grouping_col:str):
    """
    Takes in adata object from bulk data and retusn a list of organism parts

    grouping_col is the column name containing the Organism Part Information
    """
    return adata.obs[grouping_col].unique()

OPs = create_OP_list(adata, grouping_col='SMTS')




def get_genewise_averages(adata, grouping_col:str, OPs:list):
    """
    grouping_col:str is a string indicating the column name of the column you want to subset by. Example for my data is that I wnat to group by organism parts. so I will use SMTS

    OPs: List of organism parts (str)

    Purpose: Function takes adata with a column of organism parts. Calculates the average exprsesion for each gene in each organism part. And returns a matrix containing these averages
    """


    group_averages = []

    for group in OPs:
        print(f'working on {group}')

        # Subset adata by the specific group of interest
        adata_group = adata[adata.obs[grouping_col] == group]

        genewise_average = np.mean(adata_group.X, axis = 0)
        
        group_averages.append(genewise_average)

    return np.matrix(group_averages)

genewise_averages = get_genewise_averages(adata=adata, grouping_col='SMTS', OPs = OPs)




working on Adipose Tissue
working on Muscle
working on Blood Vessel
working on Heart
working on Uterus
working on Vagina
working on Breast
working on Skin
working on Salivary Gland
working on Brain
working on Adrenal Gland
working on Thyroid
working on Lung
working on Spleen
working on Pancreas
working on Esophagus
working on Stomach
working on Colon
working on Small Intestine
working on Prostate
working on Testis
working on Nerve
working on Blood
working on Pituitary
working on Ovary
working on Liver
working on Kidney
working on Cervix Uteri
working on Fallopian Tube
working on Bladder


In [103]:
genewise_averages[:,-1]

matrix([[10.832185 ],
        [ 3.7126234],
        [16.562885 ],
        [ 4.831588 ],
        [27.259022 ],
        [13.491089 ],
        [13.653842 ],
        [ 9.780465 ],
        [12.5273695],
        [16.89485  ],
        [10.6826315],
        [28.530851 ],
        [11.648892 ],
        [ 5.944318 ],
        [ 4.729068 ],
        [14.292527 ],
        [ 9.621394 ],
        [15.904528 ],
        [ 8.064366 ],
        [18.114244 ],
        [15.765406 ],
        [19.887255 ],
        [ 1.4188132],
        [30.214485 ],
        [29.435663 ],
        [ 3.0021825],
        [11.901696 ],
        [ 0.       ],
        [ 0.       ],
        [ 0.       ]], dtype=float32)

In [104]:
np.sum(np.isnan(genewise_averages), axis = 0)

matrix([[0, 0, 0, ..., 0, 0, 0]])

All NANs have been removed from the last row. Seemed to be a problem in the data

# Create PD dataframe of genewise_averages and save as a csv

In [115]:
bulk_grouped =pd.DataFrame(genewise_averages, columns=adata.var_names, index=OPs)

In [119]:
round(bulk_grouped,5)

Description      DDX11L1   WASH7P  MIR6859-1  MIR1302-2HG  FAM138A   OR4G4P  \
Adipose Tissue   0.00648  4.14990    0.01873      0.01743  0.00689  0.03939   
Muscle           0.00835  1.66335    0.00907      0.02190  0.00924  0.05379   
Blood Vessel     0.00678  4.18538    0.01245      0.01490  0.00697  0.03069   
Heart            0.00784  1.41403    0.01363      0.02632  0.01100  0.06923   
Uterus           0.01315  8.30789    0.03489      0.01640  0.00803  0.02896   
Vagina           0.01177  6.10995    0.02336      0.01395  0.00751  0.03402   
Breast           0.00725  4.84691    0.02182      0.01854  0.00712  0.04142   
Skin             0.00770  5.27628    0.02695      0.02005  0.00708  0.03783   
Salivary Gland   0.00572  3.89845    0.01258      0.01951  0.00605  0.02345   
Brain            0.01074  2.83498    0.00993      0.03433  0.01086  0.07000   
Adrenal Gland    0.01149  3.00176    0.01362      0.02265  0.00793  0.05059   
Thyroid          0.01060  6.89242    0.03931      0.02805  0.00818  0.04219   
Lung             0.01039  5.08859    0.02441      0.01843  0.00739  0.03685   
Spleen           0.01573  6.80521    0.03064      0.01699  0.00685  0.02498   
Pancreas         0.00344  2.08353    0.00887      0.00774  0.00410  0.01721   
Esophagus        0.00843  4.23619    0.01843      0.01754  0.00758  0.03944   
Stomach          0.00729  3.49109    0.03243      0.02386  0.00628  0.04525   
Colon            0.00907  4.62200    0.01509      0.02011  0.00842  0.04250   
Small Intestine  0.01065  4.97337    0.01039      0.01580  0.00690  0.04035   
Prostate         0.01168  8.02906    0.04423      0.01734  0.00775  0.04046   
Testis           0.23418  5.10289    0.02688      0.06594  0.01336  0.03303   
Nerve            0.01076  7.21337    0.03681      0.01735  0.00838  0.03522   
Blood            0.02365  3.16915    0.01796      0.01028  0.00509  0.01536   
Pituitary        0.01134  6.00119    0.05270      0.01760  0.00669  0.02991   
Ovary            0.01006  7.69715    0.02555      0.01560  0.00542  0.02218   
Liver            0.00983  1.94231    0.00635      0.02482  0.00909  0.05272   
Kidney           0.01247  3.38647    0.00466      0.03316  0.00962  0.05992   
Cervix Uteri     0.01229  6.81005    0.04193      0.01192  0.01159  0.02972   
Fallopian Tube   0.01170  6.50344    0.00000      0.00688  0.01654  0.00476   
Bladder          0.00633  5.16810    0.00000      0.01298  0.00745  0.03425   

Description      OR4G11P    OR4F5  RP11-34P13.7   CICP27  ...  RNU1-84P  \
Adipose Tissue   0.05506  0.07151       0.03495  0.04231  ...   0.00988   
Muscle           0.07922  0.11183       0.02323  0.00984  ...   0.00767   
Blood Vessel     0.04529  0.05570       0.02883  0.02969  ...   0.01419   
Heart            0.09609  0.17153       0.02409  0.01831  ...   0.00207   
Uterus           0.03813  0.04167       0.04476  0.05469  ...   0.02087   
Vagina           0.04401  0.05393       0.04716  0.10709  ...   0.02296   
Breast           0.05368  0.06762       0.04292  0.04901  ...   0.00767   
Skin             0.05055  0.06761       0.02979  0.02789  ...   0.00997   
Salivary Gland   0.04597  0.04466       0.03272  0.06278  ...   0.01112   
Brain            0.09541  0.14387       0.03865  0.03087  ...   0.01028   
Adrenal Gland    0.07593  0.11340       0.02598  0.02420  ...   0.00854   
Thyroid          0.05436  0.06970       0.05164  0.07738  ...   0.02481   
Lung             0.05226  0.05830       0.07025  0.18584  ...   0.01270   
Spleen           0.03554  0.05699       0.18010  0.54654  ...   0.01650   
Pancreas         0.02496  0.03262       0.03066  0.04121  ...   0.00381   
Esophagus        0.04973  0.06963       0.03646  0.07707  ...   0.01024   
Stomach          0.06522  0.08910       0.02616  0.04259  ...   0.00871   
Colon            0.06326  0.08404       0.02860  0.02490  ...   0.00473   
Small Intestine  0.05313  0.08107       0.02913  0.04602  ...   0.00984   
Prostate         0.05287  0.06355       0.07568  0

In [118]:
bulk_grouped.to_csv('../data/bulk/bulk_grouped.csv')